name: my_environment
channels:
  - conda-forge
dependencies:
  - python=3.10
  - dash
  - plotly
  - pandas
  - findspark
  - pyspark
  - openjdk=11
  - pymongo
  # - bokeh
  #- pip:
    # if more pip-packages needed
    # - some-other-package