#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Apr  6 23:05:39 2025

@author: willket
"""
from pymongo import MongoClient
import requests
import schedule
import time
from datetime import datetimet

# Verbindung zur MongoDB herstellen
uri = "mongodb://127.0.0.1:27017"
client = MongoClient(uri)
db = client["stockDB"]
tickers_collection = db["tickers"]
selected_tickers_collection = db["selected_tickers"]